DECLARE
  MaxTaskId NUMBER(19);
  DSql      VARCHAR2(1000);

BEGIN
  SELECT COALESCE(MAX(CTSKM_ID), 0) + 1000
  INTO MaxTaskId
  FROM CLUSTER_TASK_META;

  DSql := 'CREATE SEQUENCE CLUSTER_TASK_ID' +
          ' AS BIGINT' +
          ' START WITH ' + CONVERT(NVARCHAR, maxTaskId) +
          ' INCREMENT BY 1 CACHE 500';

  EXECUTE IMMEDIATE DSql;
END;

