SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

--
-- METADATA
--
IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CLUSTER_TASK_META'
)
  BEGIN
    CREATE TABLE [CLUSTER_TASK_META] (
      [CTSKM_ID]               [BIGINT]       NOT NULL,
      [CTSKM_TASK_TYPE]        [BIGINT]       NOT NULL,
      [CTSKM_PROCESSOR_TYPE]   [NVARCHAR](40) NOT NULL,
      [CTSKM_UNIQUENESS_KEY]   [NVARCHAR](40) NOT NULL,
      [CTSKM_CONCURRENCY_KEY]  [NVARCHAR](40) NULL,
      [CTSKM_ORDERING_FACTOR]  [BIGINT]       NULL,
      [CTSKM_CREATED]          [DATETIME]     NOT NULL,
      [CTSKM_DELAY_BY_MILLIS]  [BIGINT]       NOT NULL,
      [CTSKM_STARTED]          [DATETIME]     NULL,
      [CTSKM_RUNTIME_INSTANCE] [NVARCHAR](40) NULL,
      [CTSKM_MAX_TIME_TO_RUN]  [BIGINT]       NOT NULL,
      [CTSKM_BODY_PARTITION]   [BIGINT]       NULL,
      [CTSKM_STATUS]           [BIGINT]       NOT NULL,
      CONSTRAINT [CTSKM_PK] PRIMARY KEY CLUSTERED
        (
          [CTSKM_ID] ASC
        )
        WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
        ON [PRIMARY]
    ) ON [PRIMARY]

    CREATE UNIQUE NONCLUSTERED INDEX [CTSKM_IDX_0]
      ON [CLUSTER_TASK_META]
      (
        [CTSKM_PROCESSOR_TYPE] ASC,
        [CTSKM_UNIQUENESS_KEY] ASC
      )
      WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      ON [PRIMARY]

    CREATE NONCLUSTERED INDEX [CTSKM_IDX_1]
      ON [CLUSTER_TASK_META]
      (
        [CTSKM_STATUS] ASC,
        [CTSKM_STARTED] ASC
      )
      WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      ON [PRIMARY]

    CREATE NONCLUSTERED INDEX [CTSKM_IDX_2]
      ON [CLUSTER_TASK_META]
      (
        [CTSKM_CREATED] ASC
      )
      WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      ON [PRIMARY]

  END

--
-- TASKS' BODY - PARTITION 0
--
IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CLUSTER_TASK_BODY_P0'
)
  CREATE TABLE [CLUSTER_TASK_BODY_P0] (
    [CTSKB_ID]   [BIGINT]        NOT NULL,
    [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
    CONSTRAINT [CTSKB_PK_P0] PRIMARY KEY CLUSTERED
      (
        [CTSKB_ID] ASC
      )
      WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      ON [PRIMARY]
  ) ON [PRIMARY]
    TEXTIMAGE_ON [PRIMARY]

--
-- TASKS' BODY - PARTITION 1
--
IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CLUSTER_TASK_BODY_P1'
)
  CREATE TABLE [CLUSTER_TASK_BODY_P1] (
    [CTSKB_ID]   [BIGINT]        NOT NULL,
    [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
    CONSTRAINT [CTSKB_PK_P1] PRIMARY KEY CLUSTERED
      (
        [CTSKB_ID] ASC
      )
      WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      ON [PRIMARY]
  ) ON [PRIMARY]
    TEXTIMAGE_ON [PRIMARY]

--
-- TASKS' BODY - PARTITION 2
--
IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CLUSTER_TASK_BODY_P2'
)
  CREATE TABLE [CLUSTER_TASK_BODY_P2] (
    [CTSKB_ID]   [BIGINT]        NOT NULL,
    [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
    CONSTRAINT [CTSKB_PK_P2] PRIMARY KEY CLUSTERED
      (
        [CTSKB_ID] ASC
      )
      WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      ON [PRIMARY]
  ) ON [PRIMARY]
    TEXTIMAGE_ON [PRIMARY]

--
-- TASKS' BODY - PARTITION 3
--
IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CLUSTER_TASK_BODY_P3'
)
  CREATE TABLE [CLUSTER_TASK_BODY_P3] (
    [CTSKB_ID]   [BIGINT]        NOT NULL,
    [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
    CONSTRAINT [CTSKB_PK_P3] PRIMARY KEY CLUSTERED
      (
        [CTSKB_ID] ASC
      )
      WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
      ON [PRIMARY]
  ) ON [PRIMARY]
    TEXTIMAGE_ON [PRIMARY]