IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CTS_ACTIVE_NODES'
)
  BEGIN
    CREATE TABLE CTS_ACTIVE_NODES (
      CTSAN_NODE_ID     VARCHAR (40) CONSTRAINT CTSAN_PK PRIMARY KEY,
      CTSAN_SINCE       DATETIME    NOT NULL,
      CTSAN_LAST_SEEN   DATETIME    NOT NULL
    )
  END

DROP INDEX CTSKM_IDX_3 ON CLUSTER_TASK_META

DROP INDEX CTSKM_IDX_4 ON CLUSTER_TASK_META

ALTER TABLE CLUSTER_TASK_META DROP COLUMN CTSKM_MAX_TIME_TO_RUN

CREATE INDEX CTSKM_IDX_5 ON CLUSTER_TASK_META (CTSKM_TASK_TYPE ASC, CTSKM_RUNTIME_INSTANCE ASC)
  INCLUDE (
    CTSKM_ID,
	  CTSKM_PROCESSOR_TYPE,
	  CTSKM_BODY_PARTITION,
	  CTSKM_STATUS)

CREATE STATISTICS CTSKM_STAT_1 ON CLUSTER_TASK_META(CTSKM_RUNTIME_INSTANCE, CTSKM_TASK_TYPE)