IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CTS_ACTIVE_NODES'
)
  BEGIN
    CREATE TABLE CTS_ACTIVE_NODES (
      CTSAN_NODE_ID    VARCHAR (40) CONSTRAINT CTSAN_PK PRIMARY KEY,
      CTSAN_LAST_SEEN  DATETIME     NOT NULL
    )
  END

CREATE NONCLUSTERED INDEX CTSKM_IDX_5 ON CLUSTER_TASK_META (CTSKM_PROCESSOR_TYPE, CTSKM_STATUS)
  INCLUDE (
    CTSKM_ID,
    CTSKM_TASK_TYPE,
    CTSKM_UNIQUENESS_KEY,
    CTSKM_CONCURRENCY_KEY,
    CTSKM_ORDERING_FACTOR,
    CTSKM_CREATED,
    CTSKM_DELAY_BY_MILLIS,
    CTSKM_MAX_TIME_TO_RUN,
    CTSKM_BODY_PARTITION)

DROP INDEX CTSKM_IDX_3 ON CLUSTER_TASK_META

DROP INDEX CTSKM_IDX_4 ON CLUSTER_TASK_META