IF NOT EXISTS(
    SELECT name
    FROM sys.tables
    WHERE name = 'CTS_ACTIVE_NODES'
)
  BEGIN
    CREATE TABLE CTS_ACTIVE_NODES (
      CTSAN_NODE_ID    VARCHAR (40) CONSTRAINT CTSAN_PK PRIMARY KEY,
      CTSAN_LAST_SEEN  DATETIME     NOT NULL
    )
  END