SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--
-- METADATA
--
CREATE TABLE [CLUSTER_TASK_META] (
  [CTSKM_ID]               [BIGINT]       NOT NULL,
  [CTSKM_TASK_TYPE]        [BIGINT]       NOT NULL,
  [CTSKM_PROCESSOR_TYPE]   [NVARCHAR](40) NOT NULL,
  [CTSKM_UNIQUENESS_KEY]   [NVARCHAR](40) NOT NULL,
  [CTSKM_CONCURRENCY_KEY]  [NVARCHAR](40) NULL,
  [CTSKM_ORDERING_FACTOR]  [BIGINT]       NULL,
  [CTSKM_CREATED]          [TIMESTAMP]    NOT NULL,
  [CTSKM_DELAY_BY_MILLIS]  [BIGINT]       NOT NULL,
  [CTSKM_STARTED]          [TIMESTAMP]    NULL,
  [CTSKM_RUNTIME_INSTANCE] [NVARCHAR](40) NULL,
  [CTSKM_MAX_TIME_TO_RUN]  [BIGINT]       NOT NULL,
  [CTSKM_BODY_PARTITION]   [BIGINT]       NULL,
  [CTSKM_STATUS]           [BIGINT]       NOT NULL,
  CONSTRAINT [CTSKM_PK] PRIMARY KEY CLUSTERED
    (
      [CTSKM_ID] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    ON [PRIMARY]
) ON [PRIMARY]
GO

--
-- TASKS' BODY - PARTITION 0
--
CREATE TABLE [CLUSTER_TASK_BODY_P0] (
  [CTSKB_ID]   [BIGINT]        NOT NULL,
  [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
  CONSTRAINT [CTSKB_PK_P0] PRIMARY KEY CLUSTERED
    (
      [CTSKB_ID] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    ON [PRIMARY]
) ON [PRIMARY]
  TEXTIMAGE_ON [PRIMARY]
GO

--
-- TASKS' BODY - PARTITION 1
--
CREATE TABLE [CLUSTER_TASK_BODY_P1] (
  [CTSKB_ID]   [BIGINT]        NOT NULL,
  [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
  CONSTRAINT [CTSKB_PK_P1] PRIMARY KEY CLUSTERED
    (
      [CTSKB_ID] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    ON [PRIMARY]
) ON [PRIMARY]
  TEXTIMAGE_ON [PRIMARY]
GO

--
-- TASKS' BODY - PARTITION 2
--
CREATE TABLE [CLUSTER_TASK_BODY_P2] (
  [CTSKB_ID]   [BIGINT]        NOT NULL,
  [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
  CONSTRAINT [CTSKB_PK_P1] PRIMARY KEY CLUSTERED
    (
      [CTSKB_ID] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    ON [PRIMARY]
) ON [PRIMARY]
  TEXTIMAGE_ON [PRIMARY]
GO

--
-- TASKS' BODY - PARTITION 3
--
CREATE TABLE [CLUSTER_TASK_BODY_P3] (
  [CTSKB_ID]   [BIGINT]        NOT NULL,
  [CTSKB_BODY] [NVARCHAR](MAX) NOT NULL,
  CONSTRAINT [CTSKB_PK_P1] PRIMARY KEY CLUSTERED
    (
      [CTSKB_ID] ASC
    )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    ON [PRIMARY]
) ON [PRIMARY]
  TEXTIMAGE_ON [PRIMARY]
GO