DECLARE
  tablesFound NUMBER;

BEGIN
  SELECT COUNT(TABLE_NAME)
  INTO tablesFound
  FROM user_tables
  WHERE TABLE_NAME = 'CTS_ACTIVE_NODES';

  IF tablesFound = 0
  THEN
    EXECUTE IMMEDIATE 'CREATE TABLE CTS_ACTIVE_NODES (
      CTSAN_NODE_ID    VARCHAR2(40 CHAR) CONSTRAINT CTSAN_PK PRIMARY KEY,
      CTSAN_LAST_SEEN  DATE              NOT NULL
    )';
  END IF;
END;