DECLARE
  tablesFound NUMBER;

BEGIN
  SELECT COUNT(TABLE_NAME)
  INTO tablesFound
  FROM user_tables
  WHERE TABLE_NAME = 'CTS_ACTIVE_NODES';

  IF tablesFound = 0
  THEN
    EXECUTE IMMEDIATE 'CREATE TABLE CTS_ACTIVE_NODES (
      CTSAN_NODE_ID     VARCHAR2(40 CHAR) CONSTRAINT CTSAN_PK PRIMARY KEY,
      CTSAN_SINCE       DATE              NOT NULL,
      CTSAN_LAST_SEEN   DATE              NOT NULL
    )';
  END IF;

  EXECUTE IMMEDIATE 'DROP INDEX CTSKM_IDX_3';

  EXECUTE IMMEDIATE 'DROP INDEX CTSKM_IDX_4';

  EXECUTE IMMEDIATE 'ALTER TABLE CLUSTER_TASK_META DROP COLUMN CTSKM_MAX_TIME_TO_RUN';

  EXECUTE IMMEDIATE 'CREATE INDEX CTSKM_IDX_5 ON CLUSTER_TASK_META (
      CTSKM_PROCESSOR_TYPE,
      CTSKM_STATUS,
      CTSKM_TASK_TYPE,
      CTSKM_CREATED,
      CTSKM_ID,
      CTSKM_UNIQUENESS_KEY,
      CTSKM_CONCURRENCY_KEY,
      CTSKM_ORDERING_FACTOR,
      CTSKM_DELAY_BY_MILLIS,
      CTSKM_STARTED,
      CTSKM_RUNTIME_INSTANCE,
      CTSKM_BODY_PARTITION)';

  EXECUTE IMMEDIATE 'CREATE INDEX CTSKM_IDX_6 ON CLUSTER_TASK_META (
      CTSKM_TASK_TYPE ASC,
      CTSKM_RUNTIME_INSTANCE ASC,
      CTSKM_STATUS,
      CTSKM_ID,
      CTSKM_PROCESSOR_TYPE,
      CTSKM_BODY_PARTITION)';

END;

